import { clsx, type ClassValue } from "clsx"
import { extendTailwindMerge } from "tailwind-merge"

/**
 * Keeps class overrides deterministic for the custom Tailwind theme.
 * Without these theme keys, a merge engine cannot distinguish, for example,
 * `text-body` (font size) from `text-foreground` (color).
 */
const mergeClasses = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        'background',
        'foreground',
        'card',
        'card-foreground',
        'popover',
        'popover-foreground',
        'primary',
        'primary-foreground',
        'primary-hover',
        'primary-active',
        'secondary',
        'secondary-foreground',
        'muted',
        'muted-foreground',
        'accent',
        'accent-foreground',
        'destructive',
        'destructive-foreground',
        'error-text',
        'success',
        'success-foreground',
        'warning',
        'warning-foreground',
        'border',
        'input',
        'ring',
        'ink',
        'ink-deep',
        'ink-soft',
        'surface-card',
        'surface-raised',
        'surface-dark',
        'surface-elevated',
        'border-soft',
        'text-primary',
        'text-secondary',
        'text-muted',
        'text-accent',
        'text-coral',
        'gray-light',
        'brand-orange',
        'brand-facebook',
        'brand-google-blue',
        'brand-google-green',
        'brand-google-yellow',
        'brand-blue',
        'brand-light-blue',
        'brand-indigo',
        'chart-1',
        'chart-2',
        'chart-3',
        'chart-4',
        'chart-5',
        'sidebar',
        'sidebar-foreground',
        'sidebar-primary',
        'sidebar-primary-foreground',
        'sidebar-accent',
        'sidebar-accent-foreground',
        'sidebar-border',
        'sidebar-ring',
      ],
      text: [
        'hero',
        'display',
        'heading-lg',
        'heading',
        'title',
        'body-lg',
        'body',
        'body-sm',
        'caption',
        'tiny',
        'micro',
        'size-9',
        'size-10',
        'size-11',
        'size-12',
        'size-13',
        'size-14',
        'size-15',
        'size-16',
        'size-17',
        'size-18',
        'size-19',
        'size-20',
        'size-21',
        'size-22',
        'size-23',
        'size-24',
        'size-26',
        'size-28',
        'size-32',
        'size-43',
      ],
      leading: [
        'size-14',
        'size-15',
        'size-16',
        'size-18',
        'size-20',
        'size-22',
        'size-24',
        'size-25',
        'size-28',
        'size-29',
        'size-30',
        'size-32',
        'size-40',
        'size-45',
        'size-70',
      ],
      font: ['heading'],
      radius: ['5xl', 'control', 'shell', 'artwork'],
      shadow: ['overlay', 'overlay-mobile'],
      spacing: [
        'page-mobile',
        'page-desktop',
        'page-top-mobile',
        'page-top-desktop',
        'section-mobile',
        'section-desktop',
        'catalog-gap',
      ],
      container: ['content', 'catalog-sidebar'],
    },
  },
})

export function cn(...inputs: ClassValue[]) {
  return mergeClasses(clsx(inputs))
}
